### ISSUE TITLE
Plan for Solidity 0.6.0

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#599]
Some Solidity features we depend on are being removed in the upcoming v0.6.0. Changelog [is here](https://github.com/ethereum/solidity/blob/develop_060/docs/060-breaking-changes.rst).

> Functions can now only be overridden when they are either marked with the virtual keyword or defined in an interface. When overriding a function or modifier, the new keyword override must be used. When overriding a function or modifier defined in multiple parallel bases, all bases must be listed in parentheses after the keyword like so: override(Base1, Base2).

# Work plan

- [ ] Create new solidity-0.6 branch off of master
- [ ] Update solidity-0.6 to compile using the latest pre-release Solidity compiler
  * I'm not sure yet how to do this in Specron
- [ ] Maintain the separate solidity-0.6 branch until we want to support the new Solidity

**Comment by MoMannn** [comment]
https://github.com/0xcert/framework/pull/625
